version: '3.1'
services:
  web:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Odoo.conf
      - ./config:/etc/odoo
      
      # Enterprise addons
      - ./enterprise-17.0:/mnt/enterprise

      # Custom addons
      - ./custom-addons:/mnt/extra-addons

    ports:
      - "8069:8069"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

